services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PRACTICE_STORE_URL=http://aigents-storage-api-1:8000
      - POSTGRES_URL=postgresql://aigents:aigents_secret@aigents-storage-db-1:5432/aigents_practices
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - aigents-network
      - default

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
  aigents-network:
    external: true 